### PR TITLE
Added config for nightly builds on Azure.

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Comment by mikeller** [comment]
@DieHertz: This will need the 'Azure Pipelines' GitHub App to be installed at project level - is it possible to get this done:

image

**Review by Asizon — APPROVED** [review]
Can not do anything with this?No news from Diehertz?

**Comment by DieHertz** [comment]
@mikeller changed your project role, I can't find it myself in pending app install requests

**Comment by mikeller** [comment]
Thanks @DieHertz!

**Pull request merged**
