### PR TITLE
Added building native apps with nw.js

### PR DESCRIPTION
**Pull request by basdelfos**
I've got the basics working, following tasks must be done before final merge.
Uses the same gulp commands as Betaflight Configurator / Betaflight Log Viewer.

1. Testing on Windows and Linux (build and runtime).
2. Testing on macOS (runtime with esc's).

macOS already builds the app and DMG image.

### CODE REVIEW

**Comment by DieHertz** [comment]
Great job, thank you Bas!

**Comment by andymac4182** [comment]
I am curious if moving to a static PWA hosted with github pages is possibly a better idea than a standalone app you need to work out updates for. https://developers.google.com/web/updates/2016/03/access-usb-devices-on-the-web

**Comment by basdelfos** [comment]
Interesting for sure. But that leaves us with one practical issue; you always need an internet connection to use the BLHeli configurator, lot of people don't have internet on the field.

**Comment by DieHertz** [comment]
Surely interesting as an option for future and higher integration, standalone version should still be available.
I'll look into it.

**Comment by basdelfos** [comment]
@DieHertz when do you want to release an release candidate for the standalone configurator? The chrome app is already unlisted in the chrome web store. New users can not install it now without compiling the standalone app themselves (or install the plugin package manually, but don't expect every user to understand this).

**Comment by andymac4182** [comment]
@basdelfos You don't need internet for a PWA as it can be set up to work offline. It would just update when next online.

**Comment by basdelfos** [comment]
Really, that makes is more interesting. Let me dive into this a little bit more.

**Comment by AndersHoglund** [comment]
Good job ! 
I did a quick test build on Ubuntu and got some errors. I needed to do a few steps not mentioned in the README :

```
sudo npm install --global babel-cli
mkdir js/build
```
Then `gulp release --linux32 --linux64` seemed to work OK and produced this:
```
$ ls release
BLHeli-Configurator_linux32_1.1.0.zip  
BLHeli-Configurator_linux64_1.1.0.zip
```
Not loaded and tested them as yet.

One Q: Would you like me to setup a Jenkins job nuilding this in the same way I do BetaFligth Configurator ? I could do it now, taking the sources from basdelfos repo or wait for it to be merged here.

**Comment by basdelfos** [comment]
That `babel-cli` should be included in the dependencies in the `package.json`. I forgot to add them, will do it right away.

About the Jenkins job, that should be handy. I don't mind if you take my sources or wait until this is merged.

**Comment by basdelfos** [comment]
Wait...you needed `babel-cli` to be installed globally. Strange works on my mac without global install. Well than we need to add that to the instructions

**Comment by basdelfos** [comment]
Modified the `build-js` gulp task to create `./js/build` before compiling jsx files.

**Comment by AndersHoglund** [comment]
Thanks, that was a quick fix! Worked first time in Jenkins : http://andwho.sytes.net:8080/job/Basdelfos_BlHeli_Configurator/ 
Running from your repo for now. Once this PR  merged it makes more sense to run from the master branch of this repo.

**Pull request merged**
