### PR TITLE
Reduced ESC reset delay to match changes in boot loader and firmware.

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Review by DusKing1 — APPROVED** [review]

**Comment by Asizon** [comment]
@mikeller It looks so good for Am32, tested also for Blheli-s ESC, in this case it need i litle more bytes to be processed:

image

**Comment by Asizon** [comment]
I have found another issue flashing Blheli-S, now its no writting anithing after flash, here txo screenshots:
Now:
BLHELIs-NOWRITING
Before:
BLHELIs-WRITING

**Comment by mikeller** [comment]
@Asizon: Thanks for testing!
Re BLHeli_S, I did not change anything with the progress bar there, I think this was always only + / - accurate.
Re writing the setup, this is only done if configurator detects a difference between the current setup and the new one - so this is likely to happen when you upgrade the firmware version, but not when you re-flash the same version. Did this actually result in a problem when testing with the new version (unlikely, I did not change anything except for Open ESC code paths).

**Comment by Asizon** [comment]
@mikeller I have tried to reflash 16.7 to same 16.7 version in both configurators,1.2.0 and 1.3.0, but I can try again to verifi it.

**Comment by mikeller** [comment]
Gonna merge this, as it fixes the excessive delays when flashing Open ESC.

I want to look into improving the handling of the firmware hex objects when flashing, and this will probably result in an improvement in the progress bar calculation as well.

**Pull request merged**
